POST http://localhost:3000/auth/register
content-type: application/json

{
    "name":"leinto",
    "email":"leinto@gmail.com",
    "password":"qwerty123"
}

###

POST http://localhost:3000/auth/login
content-type: application/json

{
    "email":"leinto@gmail.com",
    "password":"qwerty123"
}

###
GET http://localhost:3000/auth/whoami
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6ImxlaW50byIsImVtYWlsIjoibGVpbnRvQGdtYWlsLmNvbSIsImlhdCI6MTY2NDE2NTg0Nn0.Nv2IQWsc08Ewa2a9BBKnCq9aOWOADTvxO-_eFpVp5L4

### CREATE CHANNEL

POST http://localhost:3000/channels
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6ImxlaW50byIsImVtYWlsIjoibGVpbnRvQGdtYWlsLmNvbSIsImlhdCI6MTY2NDE2NTg0Nn0.Nv2IQWsc08Ewa2a9BBKnCq9aOWOADTvxO-_eFpVp5L4

{
    "name":"Leinto Channels",
    "description":"Learn Code with Leinto",
    "user_id":2
}

### LIST DETAIL CHANNEL
GET http://localhost:3000/channels
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImtvaSIsImVtYWlsIjoia29pQGdtYWlsLmNvbSIsImlhdCI6MTY2NDE1NzcwNX0.zrvz-QfHmoEBVWbbJlxsUWHHed14VUcg99B8mnBnekk

### GET DETAIL CHANNEL
GET http://localhost:3000/channels/2
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImtvaSIsImVtYWlsIjoia29pQGdtYWlsLmNvbSIsImlhdCI6MTY2NDE1NzcwNX0.zrvz-QfHmoEBVWbbJlxsUWHHed14VUcg99B8mnBnekk

### CREATE VIDEOS
POST http://localhost:3000/videos
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6ImxlaW50byIsImVtYWlsIjoibGVpbnRvQGdtYWlsLmNvbSIsImlhdCI6MTY2NDE2NTg0Nn0.Nv2IQWsc08Ewa2a9BBKnCq9aOWOADTvxO-_eFpVp5L4

{
    "title":"JavaScript Async",
    "description":"We're gonna learn some JS Async",
    "channel_id":2
}

### LIST DETAIL VIDEOS
GET http://localhost:3000/videos
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImtvaSIsImVtYWlsIjoia29pQGdtYWlsLmNvbSIsImlhdCI6MTY2NDE1NzcwNX0.zrvz-QfHmoEBVWbbJlxsUWHHed14VUcg99B8mnBnekk

### GET DETAIL VIDEOS
GET http://localhost:3000/videos/2
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImtvaSIsImVtYWlsIjoia29pQGdtYWlsLmNvbSIsImlhdCI6MTY2NDE1NzcwNX0.zrvz-QfHmoEBVWbbJlxsUWHHed14VUcg99B8mnBnekk

### GET VIDEO BY CHANNEL ID
GET http://localhost:3000/videos/show/2
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6ImxlaW50byIsImVtYWlsIjoibGVpbnRvQGdtYWlsLmNvbSIsImlhdCI6MTY2NDE2NTg0Nn0.Nv2IQWsc08Ewa2a9BBKnCq9aOWOADTvxO-_eFpVp5L4